### ISSUE TITLE
Custom Parser

### ISSUE THREAD

**Issue by st-schneider** [JamieMason/astexplorer.app#13]
It would be cool if there would be in extra panel for js code for custom parsers like if I want to create a smarty template parser or something.

**Comment by JamieMason** [comment]
Hey @bm-stschneider, please could you add some more detail? I think it's likely that your request would need to be made to the main project at https://github.com/fkling/astexplorer (this project is a desktop wrapper for that) but whether this is the case would depend on what you need.

Thanks

**Comment by st-schneider** [comment]
right, you added the electron shell around that, sorry yea should bee done there.

**Comment by JamieMason** [comment]
No problem, thanks 👍
